Bug Corrections

diff --git a/functions/main b/functions/main
--- a/functions/main
+++ b/functions/main
@@ -1,7 +1,19 @@
 #Functions
 #Get ATA current IP
 CommandSSH () {
-	sshpass -p "$SSH_PASSWORD" ssh -p $SSH_PORT -o StrictHostKeyChecking=no "$SSH_USER"@"$SSH_HOST" "$SSH_COMMAND"
+	sshpass -p "$SSH_PASSWORD" ssh -p $SSH_PORT -o StrictHostKeyChecking=no "$SSH_USER"@"$SSH_HOST" "$SSH_COMMAND" 2> "$DIRTMP/ERROR"
+
+}
+
+#Error test ssh
+ErrorSSH () {
+	if [ $? != 0 ]; then
+		ERROR="$(cat $DIRTMP/ERROR)"
+		echo '---' >> "$DIRLOG/$DATE"
+		echo "$TIME" "$SSH_HOST" "$ERROR" >> "$DIRLOG/$DATE"
+		echo "CommandSSH Failed. Please, check the logs."
+		exit 1
+	fi
 }
 
 #Filter for IP Address
@@ -9,20 +21,6 @@ GrepIP () {
 	grep -E -o '([0-9]{1,3}\.){3}[0-9]{1,3}'
 }
 
-
-#Grandstream reboot
-GreandstreamTelnetReboot () {
-	(
-	  sleep 2
-	  echo "$TELNET_PASSWORD"
-	  sleep 2
-	  echo "$REBOOT_COMMAND"
-	  sleep 1
-	  echo "exit"
-	) | telnet "$TELNET_HOST" "$TELNET_PORT"
-}
-
-#Linksys reboot
-Linksys () {
-	curl "http://$CURRENTATAIP/admin/reboot"
+CleanTMP () {
+	rm -rf "$DIRTMP/*"
 }
