Error handling

diff --git a/app/scripts/functions/main b/app/scripts/functions/main
--- a/app/scripts/functions/main
+++ b/app/scripts/functions/main
@@ -1,22 +1,30 @@
-#Functions
-#Get ATA current IP
+# Functions
+# Get ATA current IP
 CommandSSH () {
-	sshpass -p "$SSH_PASSWORD" ssh -p $SSH_PORT -o StrictHostKeyChecking=no "$SSH_USER"@"$SSH_HOST" "$SSH_COMMAND" 2> "$DIRTMP/ERROR"
+	RANDOM_F="$RANDOM"
+	sshpass -p "$SSH_PASSWORD" ssh -p $SSH_PORT -o StrictHostKeyChecking=no "$SSH_USER"@"$SSH_HOST" "$SSH_COMMAND" 2> "$DIRTMP/${RANDOM_F}_ERROR"
 
 }
 
-#Error test ssh
+# Error test ssh
 ErrorSSH () {
 	if [ $? != 0 ]; then
-		ERROR="$(cat $DIRTMP/ERROR)"
-		echo '---' >> "$DIRLOG/$DATE"
-		echo "$TIME" "$SSH_HOST" "$ERROR" >> "$DIRLOG/$1_$DATE.log"
-		echo "CommandSSH Failed. Please, check the logs."
+		ERROR="$(cat $DIRTMP/${RANDOM}_ERROR)"
+		echo "$TIME" "$SSH_HOST" "$ERROR"
 		exit 1
 	fi
 }
+#
+# Script python was running successfully?
+PythonError(){
+	if [ "$?" != 0 ]; then
+		echo "Reinicialização falhou. Por favor, entre em contato com o TI de plantão e reporte o erro."
+		echo ""
+		echo "Python Script Error $DATE $TIME" && exit 1
+	fi
+}
 
-#Filter for IP Address
+# Filter for IP Address
 GrepIP () {
 	grep -E -o '([0-9]{1,3}\.){3}[0-9]{1,3}'
 }
@@ -24,3 +32,4 @@ GrepIP () {
 ClearTMP () {
 	rm -rf $DIRTMP/${RANDON_F}_main.py
 }
+
